/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <math.h>
#include <stdio.h>
#include "stm32f0xx.h"
#include "stm32_util.h"


/* 2-D array to store training data
 *   Col. 1 - x1 (acidity)
 *   Col. 2 - x2 (thickness)
 *   Col. 3 - class label
 */
uint8_t TrainData[4][3];


/* Input "test" vector */
uint8_t InVector[2];


/* Euclidean distance between input vector and the
 * training examples
 */
double Dmin[4];


/* Feature values are entered by pressing and releasing
 * one of the push buttons listed below:
 */
enum FEATURE_VALUE
{
	_User_PB = 1,
	_Red_PB,
	_Black_PB,
	_Yellow_PB,
	_White_PB,
	_Blue_PB
} __attribute__ ((packed));


/* Data collected from a questionnaire survey on people's
 * opinions regarding the quality of a particular juice.
 */
enum CLASS_LABEL
{
	Bad,
	Good
} __attribute__ ((packed));


/* Pins being used
 *  PA5-PA10, PC13
 */
enum PORT_CONNECTION
{
	USER_LED_PIN = 5,
	RED_PB,
	BLACK_PB,
	YELLOW_PB,
	WHITE_PB,
	BLUE_PB,
	BLUE_BUTTON_PIN = 13
} __attribute__ ((packed));


#define READY() 		(DigWrite ('A', USER_LED_PIN, HIGH))
#define PREDICT_GOOD()  (DigWrite ('A', USER_LED_PIN, HIGH))
#define PREDICT_BAD()	(DigWrite ('A', USER_LED_PIN,  LOW))


void KNN (void);
enum CLASS_LABEL MajorityVoting (void);


void EnterTrainingData (void);
void EnterInputData (void);
void MyDelay (void);
void Flash (uint8_t);


int main(void)
{
	Init_Pin ('A', USER_LED_PIN, OUTPUT);

	Init_Pin ('A', RED_PB, INPUT_PULLUP);
	Init_Pin ('A', BLACK_PB, INPUT_PULLUP);
	Init_Pin ('A', YELLOW_PB, INPUT_PULLUP);
	Init_Pin ('A', WHITE_PB, INPUT_PULLUP);
	Init_Pin ('A', BLUE_PB, INPUT_PULLUP);

	Init_Pin ('C', BLUE_BUTTON_PIN, INPUT_PULLUP);

    /* Loop forever */
	for(;;)
	{
		EnterTrainingData ();
		EnterInputData ();

		KNN ();

		for (uint8_t i = 0; i < 60; i++) { MyDelay (); }
		Flash (5);
		MyDelay ();
	}
}


void
KNN (void)
{
	/* K = 3 */
	for (uint8_t i = 0; i < 4; i++)
	{
		/* Difference between acidities, squared */
		Dmin[i] = pow (TrainData[i][0] - InVector[0], 2);
		/* Difference between thickness, squared */
		Dmin[i] += pow (TrainData[i][1] - InVector[1], 2);
		/* Sqrt to get Euclidean distance */
		Dmin[i] = sqrt (Dmin[i]);
	}

	if (MajorityVoting () == Good)
	{
		PREDICT_GOOD ();
	}
	else
	{
		PREDICT_BAD ();
	}
}


enum CLASS_LABEL
MajorityVoting (void)
{
	/* Find the max distance and exclude it from the vote.
	 * The remaining indices are the 3 closest neighbors
	 */
	uint8_t max = 0;
	for (uint8_t i = 0; i < 4; i++)
	{
		max = i ? Dmin[i] > Dmin[max] : max;
	}


	/* Since the class is represented as a 1 or 0,
	 * summing the 3 closest neighbors' class labels
	 * tell us the input vector's class. Classification
	 * checks if the sum is greater than sum threshold
	 * value, which in this case, is 1
	 *
	 * In general, for a binary classification based
	 * on K neighbors, the threshold value for the sum
	 * is floor (k/2).
	 */
	uint8_t neighbors = TrainData[(max + 1) % 4][2];
	neighbors += TrainData[(max + 2) % 4][2];
	neighbors += TrainData[(max + 3) % 4][2];

	Flash (10);
	if (neighbors > 1)
		return Good;
	else
		return Bad;
}


void
EnterTrainingData (void)
{
	READY ();
	printf ("Ready to enter training data >>>\n");

	uint8_t is_input;
	for (uint8_t i = 0; i < 4; i++)
	{
		is_input = 0;
		while (is_input == 0)
		{
			if (DigRead ('C', BLUE_BUTTON_PIN) == 0)
			{
				is_input = 1;
				TrainData[i][0] = _User_PB;
			}
			else if (DigRead ('A', RED_PB) == 0)
			{
				is_input = 1;
				TrainData[i][0] = _Red_PB;
			}
			else if (DigRead ('A', BLACK_PB) == 0)
			{
				is_input = 1;
				TrainData[i][0] = _Black_PB;
			}
			else if (DigRead ('A', YELLOW_PB) == 0)
			{
				is_input = 1;
				TrainData[i][0] = _Yellow_PB;
			}
			else if (DigRead ('A', WHITE_PB) == 0)
			{
				is_input = 1;
				TrainData[i][0] = _White_PB;
			}
			else if (DigRead ('A', BLUE_PB) == 0)
			{
				is_input = 1;
				TrainData[i][0] = _Blue_PB;
			}
		}

		Flash (2);
		printf ("(Training) Acidity %d accepted as %d.\n", i, TrainData[i][0]);

		is_input = 0;
		while (is_input == 0)
		{
			if (DigRead ('C', BLUE_BUTTON_PIN) == 0)
			{
				is_input = 1;
				TrainData[i][1] = _User_PB;
			}
			else if (DigRead ('A', RED_PB) == 0)
			{
				is_input = 1;
				TrainData[i][1] = _Red_PB;
			}
			else if (DigRead ('A', BLACK_PB) == 0)
			{
				is_input = 1;
				TrainData[i][1] = _Black_PB;
			}
			else if (DigRead ('A', YELLOW_PB) == 0)
			{
				is_input = 1;
				TrainData[i][1] = _Yellow_PB;
			}
			else if (DigRead ('A', WHITE_PB) == 0)
			{
				is_input = 1;
				TrainData[i][1] = _White_PB;
			}
			else if (DigRead ('A', BLUE_PB) == 0)
			{
				is_input = 1;
				TrainData[i][1] = _Blue_PB;
			}
		}

		Flash (2);
		printf ("(Training) Thickness %d accepted as %d.\n", i, TrainData[i][1]);

		is_input = 0;
		while (!is_input)
		{
			if (DigRead ('A', RED_PB) == 0)
			{
				is_input = 1;
				TrainData[i][2] = Good;
			}
			else if (DigRead ('A', BLACK_PB) == 0)
			{
				is_input = 1;
				TrainData[i][2] = Bad;
			}
		}

		Flash (2);
		printf ("(Training) Class label %d accepted as %d.\n", i, TrainData[i][2]);

		for (uint8_t j = 0; j < 4; j++) { MyDelay (); }
		READY ();
	}
}



void
EnterInputData (void)
{
	READY();
	printf ("Ready to enter input data >>>\n");

	uint8_t is_input;
	is_input = 0;
	while (is_input == 0)
	{
		if (DigRead ('C', BLUE_BUTTON_PIN) == 0)
		{
			is_input = 1;
			InVector[0] = _User_PB;
		}
		else if (DigRead ('A', RED_PB) == 0)
		{
			is_input = 1;
			InVector[0] = _Red_PB;
		}
		else if (DigRead ('A', BLACK_PB) == 0)
		{
			is_input = 1;
			InVector[0] = _Black_PB;
		}
		else if (DigRead ('A', YELLOW_PB) == 0)
		{
			is_input = 1;
			InVector[0] = _Yellow_PB;
		}
		else if (DigRead ('A', WHITE_PB) == 0)
		{
			is_input = 1;
			InVector[0] = _White_PB;
		}
		else if (DigRead ('A', BLUE_PB) == 0)
		{
			is_input = 1;
			InVector[0] = _Blue_PB;
		}
	}

	Flash (2);
	printf ("(Input) Acidity accepted as %d.\n", InVector[0]);

	is_input = 0;
	while (is_input == 0)
	{
		if (DigRead ('C', BLUE_BUTTON_PIN) == 0)
		{
			is_input = 1;
			InVector[1] = _User_PB;
		}
		else if (DigRead ('A', RED_PB) == 0)
		{
			is_input = 1;
			InVector[1] = _Red_PB;
		}
		else if (DigRead ('A', BLACK_PB) == 0)
		{
			is_input = 1;
			InVector[1] = _Black_PB;
		}
		else if (DigRead ('A', YELLOW_PB) == 0)
		{
			is_input = 1;
			InVector[1] = _Yellow_PB;
		}
		else if (DigRead ('A', WHITE_PB) == 0)
		{
			is_input = 1;
			InVector[1] = _White_PB;
		}
		else if (DigRead ('A', BLUE_PB) == 0)
		{
			is_input = 1;
			InVector[1] = _Blue_PB;
		}
	}

	Flash (2);
	printf ("(Input) Thickness accepted as %d.\n", InVector[1]);

	for (uint8_t j = 0; j < 8; j++) { MyDelay (); }
	READY ();
}


void
MyDelay (void)
{
	for (uint32_t i = 0; i < 160000; i++);
}


void
Flash (uint8_t n)
{
	for (uint8_t i = 0; i < n; i++)
	{
		DigWrite ('A', USER_LED_PIN, LOW);
		MyDelay ();
		DigWrite ('A', USER_LED_PIN, HIGH);
		MyDelay ();
	}

	DigWrite ('A', USER_LED_PIN, LOW);
}



